set dotenv-load

[no-exit-message]
recipes:
    @just --choose

install:
    @uv sync --all-extras

# Run all python linters
lint *args:
    uv run --group dev ruff check --fix {{args}}
    uv run --group dev ruff format {{args}}

# Run all tests
test *args:
    uv run --group test pytest {{args}}

# Run all tests with coverage and show it at the end
test-coverage *args:
    uv run --group test pytest --cov --cov-branch {{args}}

# Run type checking linter on Python code
typecheck *args:
    uv run --group dev ty check {{args}}

update-secrets:
    uv run --group dev detect-secrets scan --baseline .secrets.baseline

# Run all Python checks and linters + tests
ci:
    @uv run --group dev ty check
    @uv run --group dev mdformat --check
    @uv run --group dev ruff format

# Clean Python caches and various other temp files
clean:
    uv cache clean --force
