name: CI Ruby Validation

on:
  push:
    branches: [ '**' ]
    paths: ['schema-validator/**', 'config/**']
  pull_request:
    branches: [ main ]
    paths: ['schema-validator/**', 'config/**']

jobs:
  validate-schema:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: schema-validator

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '4.0.2'

    - name: Bundle Install
      run: bundle install -j 4

    - name: Validate sample game against JSON schema
      run: |
        TERM=xterm-256color bundle exec bin/schema-validator validate-json \
          --schema ../config/gomoku-json-schema.json ../gomoku-c/games
